static_resources:
  listeners:
    - name: turn_udp_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 3478
          protocol: UDP

      listener_filters:
        - name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: crowdstream-udp
            matcher:
              on_no_match:
                action:
                  name: route
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                    cluster: coturn

  clusters:
    - name: coturn
      connect_timeout: 1s
      type: STATIC
      load_assignment:
        cluster_name: coturn
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 3481
                      protocol: UDP