.PHONY: run-node-1
.PHONY: run-node-2

run-node-1:
	@echo "-----Starting one node1-------"
	INSTANCE_ID=node-1 PORT=3000 npm run dev

run-node-2:
	@echo "-----Starting one node2-------"
	INSTANCE_ID=node-2 PORT=3001 npm run dev