services:
  ngrok:
    image: ngrok/ngrok:latest
    network_mode: host
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    volumes:
      - ./ngrok.yaml:/etc/ngrok.yaml:ro
    command: start --all --config /etc/ngrok.yaml
