realm=crowdstream.local

listening-ip=127.0.0.1
relay-ip=10.41.113.15
tcp-proxy-port=3480

external-ip=10.41.113.15


fingerprint

lt-cred-mech
user=crowdstream:crowdstream-dev-password

min-port=49152
max-port=65535

simple-log
verbose

stale-nonce=600
