realm=crowdstream.local

listening-ip=127.0.0.1
relay-ip=10.254.54.255

tcp-proxy-port=3480  #tcp(haprxy)
listening-port=3481  #udp(envoy)

external-ip=10.254.54.255


fingerprint

lt-cred-mech
user=crowdstream:crowdstream-dev-password

min-port=49152
max-port=65535

simple-log
verbose

stale-nonce=600
